# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

[theme]
name = "Light Solarized"

[theme.base]
white = "#657b83"
black = "#fdf6e3"
grey = "#eee8d5"
blue = "#268bd2"
red = "#dc322f"
yellow = "#b58900"
orange = "#cb4b16"
green = "#859900"
purple = "#6c71c4"
cyan = "#2aa198"
magenta = "#d33682"

# These settings are currently pretty bad, so the text doesn't look very colorful.
# Will have to wait until Lapce is updated to where I have more and clearer options.
[theme.syntax]
attribute = "#586e75"
builtinType = "$yellow"
comment = "#93a1a1"
constant = "$magenta"
constructor = "$blue"
embedded = "$white"
enum = "$red"
enum-member = "$blue"
enumMember = "$blue"
escape = "$white"
field = "$white"
function = "$blue"
"function.method" = "$blue"
interface = "$red"
keyword = "$green"
method = "$blue"
number = "$magenta"
property = "$blue"
selfKeyword = "$green"
string = "$cyan"
struct = "$red"
structure = "$red"
type = "$red"
"type.builtin" = "$green"
typeAlias = "$red"
"variable.other.member" = "$white"

[theme.ui]
"activity.background" = "$black"
"activity.current" = "#eee8d5"
"completion.background" = "#eee8d5"
"completion.current" = "#b5890030"
"editor.background" = "$black"
"editor.caret" = "$blue"
"editor.current_line" = "#eee8d5"
"editor.dim" = "#586e75"
"editor.focus" = "#839496"
"editor.foreground" = "$white"
"editor.link" = "$cyan"
"editor.selection" = "$grey"
"hover.background" = "$black"
"lapce.active_tab" = "$black"
"lapce.border" = "#000000"
"lapce.dropdown_shadow" = "#000000"
"lapce.error" = "$red"
"lapce.inactive_tab" = "$grey"
"lapce.scroll_bar" = "$grey"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#586e75"
"palette.background" = "#eee8d5"
"palette.current" = "#b5890030"
"panel.background" = "#eee8d5"
"panel.current" = "#D6D0BF"
"panel.hovered" = "#b5890030"
"source_control.added" = "#85990032"
"source_control.modified" = "#268bd232"
"source_control.removed" = "#dc322f32"
"status.background" = "#eee8d5"
"status.modal.insert" = "$red"
"status.modal.normal" = "$blue"
"status.modal.terminal" = "$purple"
"status.modal.visual" = "$yellow"
"terminal.background" = "$black"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#eee8d5"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "$white"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"