name = "solarized"
display-name = "Solarized"
description = "Lapce themes for dark and light solarized"
version = "0.1.2"
author = "VixieTSQ"
repository = "VixieTSQ/lapce-solarized"
themes = ["dark solarized.toml"]